export const GET_CHARACTERS = 'GET_CHARACTERS';
export const CHARACTER_DETAIL = 'CHARACTER_DETAIL';
export const DETAIL_NAME = 'DETAIL_NAME';
export const CLEAN_DETAIL = 'CLEAN_DETAIL';
export const CLEAN_CHARACTER = 'CLEAN_CHARACTER';
export const CLEAN_NAME = 'CLEAN_NAME';